# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_auto_20171114_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 19, 36, 4, 926323, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 19, 36, 4, 925782, tzinfo=utc)),
        ),
    ]
